//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfiniteStorage.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfiniteStorage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string AboutTab {
            get {
                return ResourceManager.GetString("AboutTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} will sync all photos and home videos to this PC. Are you sure?.
        /// </summary>
        internal static string AllowPairingRequest {
            get {
                return ResourceManager.GetString("AllowPairingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest version installed..
        /// </summary>
        internal static string AlreadyLastestVersion {
            get {
                return ResourceManager.GetString("AlreadyLastestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back_arrow {
            get {
                object obj = ResourceManager.GetObject("back_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap backToPhone {
            get {
                object obj = ResourceManager.GetObject("backToPhone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is servicing.
        /// </summary>
        internal static string BallonText_AtService {
            get {
                return ResourceManager.GetString("BallonText_AtService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync in progress.
        /// </summary>
        internal static string BallonText_Transferring {
            get {
                return ResourceManager.GetString("BallonText_Transferring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap check {
            get {
                object obj = ResourceManager.GetObject("check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChooseThisPCOnYourPhone {
            get {
                object obj = ResourceManager.GetObject("ChooseThisPCOnYourPhone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database is imcompatible because you have installed a newer version of this product and now downgrade to an older version. Please upgrade to the latest version of Favorite Home to proceed..
        /// </summary>
        internal static string DBVersionIncompatible {
            get {
                return ResourceManager.GetString("DBVersionIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s Favorite Home.
        /// </summary>
        internal static string DefLibraryName {
            get {
                return ResourceManager.GetString("DefLibraryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlinking this device does not remove any file from this PC. Photo and home video on the device will not sync to this PC any more..
        /// </summary>
        internal static string DeleteDevice_Description {
            get {
                return ResourceManager.GetString("DeleteDevice_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlink.
        /// </summary>
        internal static string DeleteDevice_Title {
            get {
                return ResourceManager.GetString("DeleteDevice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap google_play {
            get {
                object obj = ResourceManager.GetObject("google_play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible version detected.
        /// </summary>
        internal static string IncompatibleVersionDetected {
            get {
                return ResourceManager.GetString("IncompatibleVersionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earlier this week.
        /// </summary>
        internal static string LabelName_ThisWeek {
            get {
                return ResourceManager.GetString("LabelName_ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string LabelName_Today {
            get {
                return ResourceManager.GetString("LabelName_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string LabelName_Yesterday {
            get {
                return ResourceManager.GetString("LabelName_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Backup complete.
        /// </summary>
        internal static string MenuItem_BackupComplete {
            get {
                return ResourceManager.GetString("MenuItem_BackupComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Preparing to sync.
        /// </summary>
        internal static string MenuItem_Preparing {
            get {
                return ResourceManager.GetString("MenuItem_Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory {0} is not empty..
        /// </summary>
        internal static string MoveFolder_TargetAlreadyExist {
            get {
                return ResourceManager.GetString("MoveFolder_TargetAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will move the Favorite Home folder and all the files inside from its current location to {0}..
        /// </summary>
        internal static string MoveFolderConfirmMsg {
            get {
                return ResourceManager.GetString("MoveFolderConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move folder unsuccessful.
        /// </summary>
        internal static string MoveFolderFailTitle {
            get {
                return ResourceManager.GetString("MoveFolderFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap photography_camera {
            get {
                object obj = ResourceManager.GetObject("photography_camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ProductIcon {
            get {
                object obj = ResourceManager.GetObject("ProductIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Home.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File synced from {0}.
        /// </summary>
        internal static string ProgressTooltip {
            get {
                return ResourceManager.GetString("ProgressTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import complete: {0} / {1}.
        /// </summary>
        internal static string ProgressTooltip_Complete {
            get {
                return ResourceManager.GetString("ProgressTooltip_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device disconnected: {0} / {1}.
        /// </summary>
        internal static string ProgressTooltip_Interrupted {
            get {
                return ResourceManager.GetString("ProgressTooltip_Interrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress: {0} / {1} ({2}%).
        /// </summary>
        internal static string ProgressTooltip_Progress {
            get {
                return ResourceManager.GetString("ProgressTooltip_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Scanning {
            get {
                object obj = ResourceManager.GetObject("Scanning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tea_Cup1 {
            get {
                object obj = ResourceManager.GetObject("Tea_Cup1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string TrayMenuItem_Open {
            get {
                return ResourceManager.GetString("TrayMenuItem_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open backup folder.
        /// </summary>
        internal static string TrayMenuItem_OpenBackupFolder {
            get {
                return ResourceManager.GetString("TrayMenuItem_OpenBackupFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefereces....
        /// </summary>
        internal static string TrayMenuItem_Preferences {
            get {
                return ResourceManager.GetString("TrayMenuItem_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string TrayMenuItem_Quit {
            get {
                return ResourceManager.GetString("TrayMenuItem_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsorted.
        /// </summary>
        internal static string UnsortedFolderName {
            get {
                return ResourceManager.GetString("UnsortedFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version：{0}.
        /// </summary>
        internal static string VersionLable {
            get {
                return ResourceManager.GetString("VersionLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap video {
            get {
                object obj = ResourceManager.GetObject("video", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available Favorite Uploader device is found. Search again?.
        /// </summary>
        internal static string WaitForPair_SearchAgainMsg {
            get {
                return ResourceManager.GetString("WaitForPair_SearchAgainMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No device found.
        /// </summary>
        internal static string WaitForPair_SearchAgainTitle {
            get {
                return ResourceManager.GetString("WaitForPair_SearchAgainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Waiting {
            get {
                object obj = ResourceManager.GetObject("Waiting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
