//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfiniteStorage.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfiniteStorage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關於{0}.
        /// </summary>
        internal static string AboutTab {
            get {
                return ResourceManager.GetString("AboutTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允許 {0} 備份檔案到這台電腦?.
        /// </summary>
        internal static string AllowPairingRequest {
            get {
                return ResourceManager.GetString("AllowPairingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您的 Bunny 已經是最新的版本.
        /// </summary>
        internal static string AlreadyLastestVersion {
            get {
                return ResourceManager.GetString("AlreadyLastestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案：準備中.
        /// </summary>
        internal static string BackupProgressFile_Preparing {
            get {
                return ResourceManager.GetString("BackupProgressFile_Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 裝置中所有 {0} 個檔案都已備份到此電腦中.
        /// </summary>
        internal static string BackupProgressTitle_BackupComplete {
            get {
                return ResourceManager.GetString("BackupProgressTitle_BackupComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 已結束備份.
        /// </summary>
        internal static string BackupProgressTitle_Finished {
            get {
                return ResourceManager.GetString("BackupProgressTitle_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 正在備份到這台電腦.
        /// </summary>
        internal static string BackupProgressTitle_InProgress {
            get {
                return ResourceManager.GetString("BackupProgressTitle_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 在此為您服務.
        /// </summary>
        internal static string BallonText_AtService {
            get {
                return ResourceManager.GetString("BallonText_AtService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 正在備份中....
        /// </summary>
        internal static string BallonText_Transferring {
            get {
                return ResourceManager.GetString("BallonText_Transferring", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ChooseThisPCOnYourPhone {
            get {
                object obj = ResourceManager.GetObject("ChooseThisPCOnYourPhone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除您的裝置以後，已存入的檔案不會被刪除。
        ///往後這台裝置中的照片、影片、錄音檔案將不會再送回此電腦中。.
        /// </summary>
        internal static string DeleteDevice_Description {
            get {
                return ResourceManager.GetString("DeleteDevice_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除裝置.
        /// </summary>
        internal static string DeleteDevice_Title {
            get {
                return ResourceManager.GetString("DeleteDevice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案：{0}   {1} bytes.
        /// </summary>
        internal static string FirstUse_FileLabel {
            get {
                return ResourceManager.GetString("FirstUse_FileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請回到手機，指定備份到這台電腦 - {0}.
        /// </summary>
        internal static string FirstUse_Instruction1 {
            get {
                return ResourceManager.GetString("FirstUse_Instruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一步.
        /// </summary>
        internal static string FirstUse_Next {
            get {
                return ResourceManager.GetString("FirstUse_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您尚未完成設定程序，請按下一步.
        /// </summary>
        internal static string FirstUse_NoExitBeforeAcceptComplete {
            get {
                return ResourceManager.GetString("FirstUse_NoExitBeforeAcceptComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 進度：{0}/{1}.
        /// </summary>
        internal static string FirstUse_ProgressLabel {
            get {
                return ResourceManager.GetString("FirstUse_ProgressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 縮到狀態列.
        /// </summary>
        internal static string FirstUse_ShrinkToSystemTray {
            get {
                return ResourceManager.GetString("FirstUse_ShrinkToSystemTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開始備份.
        /// </summary>
        internal static string FirstUse_Start {
            get {
                return ResourceManager.GetString("FirstUse_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 備份了 {1} 個檔案.
        /// </summary>
        internal static string FirstUse_TransferStopped {
            get {
                return ResourceManager.GetString("FirstUse_TransferStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - 備份完成.
        /// </summary>
        internal static string MenuItem_BackupComplete {
            get {
                return ResourceManager.GetString("MenuItem_BackupComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - 準備傳送中....
        /// </summary>
        internal static string MenuItem_Preparing {
            get {
                return ResourceManager.GetString("MenuItem_Preparing", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon product_icon {
            get {
                object obj = ResourceManager.GetObject("product_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bunny.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Tea_Cup1 {
            get {
                object obj = ResourceManager.GetObject("Tea_Cup1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting started....
        /// </summary>
        internal static string TrayMenuItem_GettingStarted {
            get {
                return ResourceManager.GetString("TrayMenuItem_GettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開啟備份資料夾.
        /// </summary>
        internal static string TrayMenuItem_OpenBackupFolder {
            get {
                return ResourceManager.GetString("TrayMenuItem_OpenBackupFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定....
        /// </summary>
        internal static string TrayMenuItem_Preferences {
            get {
                return ResourceManager.GetString("TrayMenuItem_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關閉.
        /// </summary>
        internal static string TrayMenuItem_Quit {
            get {
                return ResourceManager.GetString("TrayMenuItem_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 備份中：({1}/{2}).
        /// </summary>
        internal static string TrayMenuItem_Transfering {
            get {
                return ResourceManager.GetString("TrayMenuItem_Transfering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本：{0}.
        /// </summary>
        internal static string VersionLable {
            get {
                return ResourceManager.GetString("VersionLable", resourceCulture);
            }
        }
    }
}
